# Generated by Django 5.1 on 2024-09-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_gallary'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallary',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gallary',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
