# Generated by Django 5.1 on 2024-09-04 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_gallary_created_at_gallary_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallary',
            options={'verbose_name_plural': 'Gallary'},
        ),
        migrations.RemoveField(
            model_name='gallary',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='gallary',
            name='updated_at',
        ),
    ]
