# Generated by Django 5.1 on 2024-09-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_gallary_options_remove_gallary_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='gallary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
