# Generated by Django 5.1 on 2024-09-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_contact_icon_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('class_name', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Icon',
                'ordering': ['name'],
            },
        ),
    ]
