# Generated by Django 5.1 on 2024-09-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='icon_class',
        ),
        migrations.AddField(
            model_name='contact',
            name='icons',
            field=models.ManyToManyField(blank=True, to='home.icon'),
        ),
    ]
