# Generated by Django 5.1 on 2024-09-05 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_contact_created_at_contact_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='Notice/')),
            ],
            options={
                'verbose_name_plural': 'Notice',
                'ordering': ['-id'],
            },
        ),
    ]
