# Generated by Django 5.1 on 2024-09-05 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=255, verbose_name='পরীক্ষার নাম')),
                ('year', models.IntegerField(verbose_name='সাল')),
                ('total_students', models.PositiveIntegerField(verbose_name='মোট পরীক্ষার্থী')),
                ('passing_students_boys', models.PositiveIntegerField(verbose_name='পাসকৃত শিক্ষার্থী (Boys)')),
                ('passing_students_girls', models.PositiveIntegerField(verbose_name='পাসকৃত শিক্ষার্থী (Girls)')),
                ('gpa_5_boys', models.PositiveIntegerField(verbose_name='জিপিএ ৫.০০ (Boys)')),
                ('gpa_5_girls', models.PositiveIntegerField(verbose_name='জিপিএ ৫.০০ (Girls)')),
                ('pass_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='পাসের হার')),
            ],
            options={
                'verbose_name_plural': 'Exam Result',
                'ordering': ['-year'],
            },
        ),
    ]
