# Generated by Django 5.1 on 2024-09-05 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_examresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eiin', models.CharField(max_length=15, verbose_name='বিদ্যালয়ের EIIN')),
                ('school_name_bn', models.CharField(max_length=255, verbose_name='বিদ্যালয়ের নাম')),
                ('school_name_en', models.CharField(max_length=255, verbose_name='SCHOOL NAME')),
                ('address', models.TextField(verbose_name='গ্রাম/বাড়ী ও সড়কের বিবরণ')),
                ('ward_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='ওয়ার্ড নম্বর')),
                ('post_office', models.CharField(max_length=100, verbose_name='পোস্ট অফিস')),
                ('police_station', models.CharField(max_length=100, verbose_name='পুলিশ স্টেশন')),
                ('district', models.CharField(max_length=100, verbose_name='জেলা')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='মোবাইল')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('school_shift', models.CharField(blank=True, max_length=50, null=True, verbose_name='বিদ্যালয়ের শিফট')),
                ('class_operations', models.CharField(blank=True, max_length=100, null=True, verbose_name='শ্রেণি কার্যক্রম')),
                ('total_land_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='মোট জমির পরিমান (একর)')),
                ('total_classrooms', models.PositiveIntegerField(blank=True, null=True, verbose_name='মোট শ্রেণিকক্ষ সংখ্যা')),
                ('ict_lab_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='আইসিটি ল্যাব সংখ্যা')),
                ('library_room_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='পাঠাগার এর জন্য কক্ষ সংখ্যা')),
                ('has_boundary_wall', models.BooleanField(default=False, verbose_name='সীমানা প্রাচীর আছে কি না')),
                ('has_playground', models.BooleanField(default=False, verbose_name='খেলার মাঠ আছে কি না')),
                ('union_or_municipality', models.CharField(blank=True, max_length=100, null=True, verbose_name='ইউনিয়ন/পৌরসভা/সিটি কর্পোরেশন')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='পোস্ট কোড')),
                ('upazila', models.CharField(blank=True, max_length=100, null=True, verbose_name='উপজেলা')),
                ('division', models.CharField(max_length=100, verbose_name='বিভাগ')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail')),
                ('total_students', models.PositiveIntegerField(blank=True, null=True, verbose_name='শিক্ষার্থীর সংখ্যা')),
                ('school_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='বিদ্যালয়ের ধরণ')),
                ('building_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='ভবন সংখ্যা')),
                ('multimedia_classroom_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='মাল্টিমিডিয়া শ্রেণিকক্ষ সংখ্যা')),
                ('science_lab_room_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='বিজ্ঞানাগার এর জন্য কক্ষ সংখ্যা')),
                ('has_auditorium', models.BooleanField(default=False, verbose_name='অডিটোরিয়াম আছে কি না')),
            ],
            options={
                'verbose_name_plural': 'এক নজরে বিদ্যালয়ের পরিচিতি',
                'ordering': ['-id'],
            },
        ),
    ]
