# Generated by Django 5.1 on 2024-09-05 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_schoolinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_class', models.CharField(choices=[('Six', 'Six'), ('Seven', 'Seven'), ('Eight', 'Eight'), ('Nine', 'Nine'), ('Ten', 'Ten')], max_length=20, verbose_name='শ্রেণি')),
                ('shift', models.CharField(choices=[('Morning', 'Morning'), ('Day', 'Day'), ('Evening', 'Evening')], max_length=20, verbose_name='শিফট')),
                ('section', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=5, null=True, verbose_name='সেকশন')),
                ('total_students', models.PositiveIntegerField(verbose_name='মোট শিক্ষার্থী সংখ্যা')),
                ('boys', models.PositiveIntegerField(verbose_name='ছেলে শিক্ষার্থী সংখ্যা')),
                ('girls', models.PositiveIntegerField(verbose_name='মেয়ে শিক্ষার্থী সংখ্যা')),
                ('muslim_students', models.PositiveIntegerField(verbose_name='মুসলিম শিক্ষার্থী সংখ্যা')),
                ('hindu_students', models.PositiveIntegerField(verbose_name='হিন্দু শিক্ষার্থী সংখ্যা')),
                ('buddhist_students', models.PositiveIntegerField(blank=True, null=True, verbose_name='বৌদ্ধ শিক্ষার্থী সংখ্যা')),
                ('christian_students', models.PositiveIntegerField(blank=True, null=True, verbose_name='খ্রিস্টান শিক্ষার্থী সংখ্যা')),
                ('science_students', models.PositiveIntegerField(blank=True, null=True, verbose_name='বিজ্ঞান বিভাগে শিক্ষার্থী সংখ্যা')),
                ('commerce_students', models.PositiveIntegerField(blank=True, null=True, verbose_name='ব্যবসা শিক্ষা বিভাগে শিক্ষার্থী সংখ্যা')),
                ('humanities_students', models.PositiveIntegerField(blank=True, null=True, verbose_name='মানবিক বিভাগে শিক্ষার্থী সংখ্যা')),
                ('freedom_fighter_children', models.PositiveIntegerField(blank=True, null=True, verbose_name='মুক্তিযোদ্ধার সন্তান শিক্ষার্থী সংখ্যা')),
                ('freedom_fighter_grandchildren', models.PositiveIntegerField(blank=True, null=True, verbose_name='মুক্তিযোদ্ধার স.সন্তান শিক্ষার্থী সংখ্যা')),
                ('disabled_students_total', models.PositiveIntegerField(blank=True, null=True, verbose_name='মোট প্রতিবন্ধি শিক্ষার্থী সংখ্যা')),
                ('autistic_students', models.PositiveIntegerField(blank=True, null=True, verbose_name='অটিস্টিক শিক্ষার্থী সংখ্যা')),
                ('physically_disabled_students', models.PositiveIntegerField(blank=True, null=True, verbose_name='শারীরিক প্রতিবন্ধি শিক্ষার্থী সংখ্যা')),
            ],
            options={
                'verbose_name_plural': 'এক নজরে শ্রেণির তথ্য',
                'ordering': ['student_class', 'shift', 'section'],
            },
        ),
    ]
