# Generated by Django 5.1.1 on 2024-10-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_studentadmission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-id'], 'verbose_name_plural': 'যোগাযোগ'},
        ),
        migrations.AlterModelOptions(
            name='importantlink',
            options={'ordering': ['-id'], 'verbose_name_plural': 'গুরুত্বপূর্ণ লিঙ্ক'},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-id'], 'verbose_name_plural': 'নোটিশ বোর্ড'},
        ),
        migrations.AlterModelOptions(
            name='qoutes',
            options={'ordering': ['writer_name'], 'verbose_name_plural': 'অনুপ্রেরণামূলক উক্তি সমগ্র'},
        ),
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'ordering': ['-id'], 'verbose_name_plural': 'সামাজিক যোগাযোগ মাধ্যম'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['name'], 'verbose_name_plural': 'শিক্ষকবৃন্দ'},
        ),
        migrations.AlterField(
            model_name='importantlink',
            name='link',
            field=models.URLField(max_length=500, verbose_name='লিঙ্ক'),
        ),
        migrations.AlterField(
            model_name='importantlink',
            name='link_name',
            field=models.CharField(max_length=100, verbose_name='লিঙ্ক Name'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='Notice/', verbose_name='নোটিশ তথ্য PDF'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.TextField(verbose_name='শিরোনাম'),
        ),
    ]
