# Generated by Django 5.1.3 on 2024-11-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_contact_options_alter_importantlink_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='total_boys',
            field=models.PositiveIntegerField(default=0, verbose_name='মোট পরীক্ষার্থী (Boys)'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='total_girls',
            field=models.PositiveIntegerField(default=0, verbose_name='মোট পরীক্ষার্থী (Girls)'),
        ),
    ]
