# Generated by Django 5.1.3 on 2024-11-10 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_introductionschool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introductionschool',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='জেলা'),
        ),
        migrations.AlterField(
            model_name='introductionschool',
            name='division',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='বিভাগ'),
        ),
        migrations.AlterField(
            model_name='introductionschool',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='introductionschool',
            name='has_auditorium',
            field=models.BooleanField(blank=True, null=True, verbose_name='অডিটোরিয়াম আছে কি না'),
        ),
        migrations.AlterField(
            model_name='introductionschool',
            name='has_boundary',
            field=models.BooleanField(blank=True, null=True, verbose_name='সীমানা প্রাচীর আছে কি না'),
        ),
        migrations.AlterField(
            model_name='introductionschool',
            name='has_playground',
            field=models.BooleanField(blank=True, null=True, verbose_name='খেলার মাঠ আছে কি না'),
        ),
        migrations.AlterField(
            model_name='introductionschool',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='মোবাইল'),
        ),
        migrations.AlterField(
            model_name='introductionschool',
            name='police_station',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='পুলিশ স্টেশন'),
        ),
        migrations.AlterField(
            model_name='introductionschool',
            name='post_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='পোস্ট কোড'),
        ),
        migrations.AlterField(
            model_name='introductionschool',
            name='post_office',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='পোস্ট অফিস'),
        ),
        migrations.AlterField(
            model_name='introductionschool',
            name='school_activites',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='শ্রেণি কার্যক্রম'),
        ),
        migrations.AlterField(
            model_name='introductionschool',
            name='school_chars',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='বিদ্যালয়ের ধরণ'),
        ),
        migrations.AlterField(
            model_name='introductionschool',
            name='school_elln',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='বিদ্যালয়ের EIIN'),
        ),
        migrations.AlterField(
            model_name='introductionschool',
            name='school_name_bn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='বিদ্যালয়ের নাম'),
        ),
        migrations.AlterField(
            model_name='introductionschool',
            name='school_name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SCHOOL NAME'),
        ),
        migrations.AlterField(
            model_name='introductionschool',
            name='school_shit',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='বিদ্যালয়ের শিফট'),
        ),
        migrations.AlterField(
            model_name='introductionschool',
            name='total_classroom',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='মোট শ্রেণিকক্ষ সংখ্যা'),
        ),
        migrations.AlterField(
            model_name='introductionschool',
            name='total_ict_lab',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='আইসিটি ল্যাব সংখ্যা'),
        ),
        migrations.AlterField(
            model_name='introductionschool',
            name='total_land',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='মোট জমির পরিমান (একর)'),
        ),
        migrations.AlterField(
            model_name='introductionschool',
            name='total_library_room',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='পাঠাগার এর জন্য কক্ষ সংখ্যা'),
        ),
        migrations.AlterField(
            model_name='introductionschool',
            name='total_multimedia_room',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='মাল্টিমিডিয়া শ্রেণিকক্ষ সংখ্যা'),
        ),
        migrations.AlterField(
            model_name='introductionschool',
            name='total_room_for_science',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='বিজ্ঞানাগার এর জন্য কক্ষ সংখ্যা'),
        ),
        migrations.AlterField(
            model_name='introductionschool',
            name='total_students',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='শিক্ষার্থীর সংখ্যা'),
        ),
        migrations.AlterField(
            model_name='introductionschool',
            name='total_vobon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ভবন সংখ্যা'),
        ),
        migrations.AlterField(
            model_name='introductionschool',
            name='union_city_corparation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ইউনিয়ন/পৌরসভা/সিটি কর্পোরেশন'),
        ),
        migrations.AlterField(
            model_name='introductionschool',
            name='upozila',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='উপজেলা'),
        ),
        migrations.AlterField(
            model_name='introductionschool',
            name='village_or_road',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='গ্রাম/বাড়ী ও সড়কের বিবরণ'),
        ),
        migrations.AlterField(
            model_name='introductionschool',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='introductionschool',
            name='word_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ওয়ার্ড নম্বর'),
        ),
    ]
